version: '3'

services:

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - djangonetwork

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
  djangonetwork:
    external: true
