version: '3'

services:

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - djangonetwork

  web:
    build: .
    command: gunicorn --workers=20 --threads=2 --bind 0.0.0.0:8000 noise_dashboard.wsgi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    networks:
      - djangonetwork

  mqtt:
    build: .
    command: python /code/mqtt_client.py
    volumes:
      - .:/code
    depends_on:
      - web
    links:
      - postgres_db:postgres_db
    networks:
      - djangonetwork
    environment:
      - MOSQUITTO_URL=Mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: Mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/
    networks:
      - djangonetwork
    restart: unless-stopped

  influxdb:
    image: influxdb:2.0.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  postgres_data:
  influxdb:
  grafana-data:

networks:
  djangonetwork:
    external: true
