# Generated by Django 3.2.6 on 2021-08-06 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200)),
                ('imei', models.CharField(max_length=15)),
                ('device_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('production_stage', models.CharField(choices=[('DL', 'Deployed'), ('TS', 'Testing'), ('RC', 'Recalled'), ('FX', 'Fixing')], default='TS', max_length=2)),
                ('tags', models.ManyToManyField(to='devices.Tag')),
            ],
        ),
    ]
