# Generated by Django 3.2.6 on 2021-08-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
