# Generated by Django 3.2.6 on 2021-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_production_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='production_stage',
            field=models.CharField(choices=[('Deployed', 'Deployed'), ('Testing', 'Testing'), ('Shelved', 'Shelved'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Testing', max_length=50),
        ),
    ]
