# Generated by Django 3.2.6 on 2021-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210811_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='version_number',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
