# Generated by Django 3.2.6 on 2021-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='metrics_url',
            field=models.URLField(default='http://34.245.125.169:3001/', max_length=255),
        ),
    ]
