# Generated by Django 3.2.6 on 2021-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_metrics_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='metrics_url',
            field=models.URLField(default='http://localhost:3000/', max_length=255),
        ),
    ]
