# Generated by Django 3.2.6 on 2021-08-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_device_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devices.device')),
                ('configured', models.IntegerField(choices=[(1, 'Configured'), (0, 'Not Configured')], default=0)),
                ('mode', models.IntegerField(choices=[(1, 'Auto Mode'), (2, 'Manual Mode')], default=1)),
                ('dbLevel', models.IntegerField(default=50)),
                ('recLength', models.IntegerField(default=10)),
                ('recInterval', models.IntegerField(default=10)),
                ('uploadAddr', models.CharField(default='http://localhost:8000/audio/', max_length=100)),
            ],
        ),
    ]
