# Generated by Django 3.2.6 on 2021-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_deviceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configured',
            field=models.IntegerField(choices=[(1, 'Configured'), (0, 'Not Configured')], default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='dbLevel',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Auto'), (2, 'Manual')], default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='recInterval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='device',
            name='recLength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='device',
            name='uploadAddr',
            field=models.CharField(default='http://localhost:8000/audio/', max_length=100),
        ),
        migrations.DeleteModel(
            name='DeviceConfiguration',
        ),
    ]
