# Generated by Django 3.2.6 on 2022-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20220104_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='place_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
