# Generated by Django 3.2.6 on 2022-02-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20220126_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
