# Generated by Django 3.2.6 on 2022-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_auto_20220207_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place_name',
        ),
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='parish',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='village',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
