# Generated by Django 3.2.6 on 2022-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_location_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('A', 'Category A: hospital, convalescence home, sanatorium, home for the aged and higher learning institute, conference rooms, public library, environmental or recreational sites'), ('B', 'Category B: Residential buildings'), ('C', 'Category C: Mixed residential (with some commercial and entertainment)'), ('D', 'Category D: Residential + industry or small-scale production + commerce'), ('E', 'Category E: Industrial')], default='E', max_length=50),
        ),
    ]
