# Generated by Django 3.2.6 on 2024-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastSeen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
