# Generated by Django 3.2.6 on 2024-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_device_lastseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='lastSeen',
        ),
    ]
