# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0020_remove_device_lastseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("MCU", "MCU"), ("MPU", "MPU")],
                default="",
                max_length=10,
            ),
        ),
    ]
