# Generated by Django 3.2.6 on 2021-08-25 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_alter_device_metrics_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_name', models.CharField(max_length=50)),
                ('time_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_uploaded', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='audio/')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
