# Generated by Django 3.2.6 on 2021-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='file',
            new_name='audio',
        ),
    ]
