# Generated by Django 3.2.6 on 2021-08-31 13:21

from django.db import migrations, models
import recordings.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_rename_file_recording_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='recording_name',
        ),
        migrations.AddField(
            model_name='recording',
            name='triggering_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio',
            field=models.FileField(upload_to=recordings.models.recording_directory),
        ),
    ]
