# Generated by Django 3.2.6 on 2022-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemetrics',
            old_name='datetime_uploaded',
            new_name='time_uploaded',
        ),
    ]
