# Generated by Django 3.2.6 on 2022-02-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_metrics', '0002_rename_datetime_uploaded_devicemetrics_time_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemetrics',
            name='avg_db_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='devicemetrics',
            name='max_db_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='devicemetrics',
            name='no_of_exceedances',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='db_level',
            field=models.FloatField(),
        ),
    ]
