# Generated by Django 3.2.6 on 2024-08-05 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device_metrics', '0005_environmentalparameter_soundinferencedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentalparameter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='soundinferencedata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Sound Inference Data'},
        ),
        migrations.AddField(
            model_name='environmentalparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentalparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soundinferencedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundinferencedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
