# Generated by Django 3.2.6 on 2025-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_metrics', '0006_auto_20240805_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalparameter',
            name='db_level',
            field=models.FloatField(default=0.0, help_text='Decibel level'),
        ),
    ]
