# Generated by Django 3.2.6 on 2026-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_metrics', '0007_environmentalparameter_db_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemetrics',
            name='last_rec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='last_upl',
            field=models.FloatField(),
        ),
    ]
