# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_metrics", "0008_auto_20260516_0816"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicemetrics",
            index=models.Index(
                fields=["device", "-time_uploaded"],
                name="devmetrics_device_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="environmentalparameter",
            index=models.Index(
                fields=["device", "-created_at"],
                name="envparam_device_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="soundinferencedata",
            index=models.Index(
                fields=["device", "-created_at"],
                name="soundinf_device_created_idx",
            ),
        ),
    ]
