# Generated by Django 3.2.6 on 2022-10-17 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
        ('analysis', '0002_alter_dailyanalysis_daily_no_of_exceedances'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalysis',
            name='daily_median_db_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='date_analyzed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='daily_avg_db_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='daily_max_db_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='daily_no_of_exceedances',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HourlyAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_analyzed', models.DateTimeField(default=django.utils.timezone.now)),
                ('hour_analyzed', models.PositiveIntegerField(null=True)),
                ('hourly_avg_db_level', models.FloatField(null=True)),
                ('hourly_median_db_level', models.FloatField(null=True)),
                ('hourly_max_db_level', models.FloatField(null=True)),
                ('hourly_no_of_exceedances', models.PositiveIntegerField(null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
