# Generated by Django 3.2.6 on 2022-10-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
        ('analysis', '0003_auto_20221017_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyAnalysis',
            new_name='DailyAggregate',
        ),
        migrations.RenameModel(
            old_name='HourlyAnalysis',
            new_name='HourlyAggregate',
        ),
        migrations.RenameField(
            model_name='dailyaggregate',
            old_name='date_analyzed',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='hourlyaggregate',
            old_name='date_analyzed',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='hourlyaggregate',
            old_name='hour_analyzed',
            new_name='hour',
        ),
    ]
