# Generated by Django 3.2.6 on 2022-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20221024_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyaggregate',
            name='device',
        ),
        migrations.RemoveField(
            model_name='hourlyaggregate',
            name='device',
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hourlyaggregate',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
