# Generated by Django 3.2.6 on 2022-11-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
        ('analysis', '0005_auto_20221024_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddField(
            model_name='hourlyaggregate',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
