# Generated by Django 3.2.6 on 2022-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
        ('analysis', '0006_auto_20221110_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaggregate',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyaggregate',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
    ]
