# Generated by Django 3.2.6 on 2022-11-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20221110_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyaggregate',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='hourlyaggregate',
            name='device_name',
        ),
    ]
