# Generated by Django 3.2.6 on 2023-04-18 10:07

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_location_category'),
        ('analysis', '0009_dailyaggregate_time_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsTextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_uploaded', models.DateTimeField(auto_now_add=True)),
                ('metrics_file', models.FileField(upload_to=analysis.models.recording_directory)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
